
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.23
    volumes:
      - elasticsearch_volume:/usr/share/elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
  
  kibana:
    container_name: kibana
    image: kibana:7.17.23
    volumes:
      - kibana_volume:/usr/share/kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_HOST}
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_volume:
    external: false

  kibana_volume:
    external: false
